### ISSUE TITLE
Error linking game

### ISSUE THREAD

**Issue by kateract** [mixer/cdk#110] opened 2018-05-12 16:57 UTC
### Steps to Reproduce
Opened the quick start for html/javascript
Went through tutorial 
Clicked Run => On my channel Page
Clicked off because I didn't want to mess with my existing game configs
Created new game on mixer dev lab
Clicked Run => On my channel Page
Get this error before being able to choose a game.

### Error

{
  "message": "Unexpected status code 404 Not Found from https://mixer.com/api/v1/interactive/versions/39637: {\"message\":\"InteractiveBundle not found.\",\"statusCode\":404,\"error\":\"Not Found\"}",
  "stack": "Error: Unexpected status code 404 Not ...

### Editor Details

**Version**: 1.0.0
**Mixer User ID**: 486466

**Encrypted Editor State**: `{"id":"c7face4856b5ada0","password":"JjHX/9OEDIr/b9RYip1Sw5RuL5aWhmuECnDUoIWvU5Y="}`

**Comment by connor4312** [comment] 2018-06-06 23:33
Could not reproduce on v1.0.1, marking as fixed pending further reproductions.

**Closed by connor4312** 2018-06-06 23:33 UTC
Labels: bug
