### ISSUE TITLE
Lack of error messaging when uploading a bundle with a taken name.

### ISSUE THREAD

**Issue by jthrockmorton** [mixer/cdk#114] opened 2018-05-23 00:34 UTC
The upload screen simply "hangs" when the user tries to upload a bundle with a name that has already been taken. There is no apparent error messaging to inform the user why the process doesn't complete.

**Comment by connor4312** [comment] 2018-05-23 17:11
Duplicate of #99

**Closed by connor4312** 2018-05-23 17:11 UTC
Labels: bug
